### ISSUE TITLE
500 Error: The key 'sf.passport.verifier.oauth2ClientPassword' is not bound to any value in context application

### ISSUE THREAD

**Issue by vikramkh** [sourcefuse/loopback4-authentication#1] opened 2019-06-03 09:06 UTC
**Describe the bug**
I followed the instructions for loopback4-authentication and when I run the loopback server, it starts, but when I try to go to the actual page on the web, I get the error: 
500 Error: The key 'sf.passport.verifier.oauth2ClientPassword' is not bound to any value in context application
 at MealPlanApplication.getBinding (/Users/me/Desktop/folder/folder/node_modules/@loopback/context/dist/context.js:503:15)
I'm not sure how to fix/what is wrong exactly.

**Comment by samarpan-b** [comment] 2019-06-04 09:54
@vikramkh it seems you have missed the ClientPasswordVerifyProvider. You can refer to the docs [here](https://github.com/sourcefuse/loopback4-authentication#oauth2-client-password) for a sample implementation. 

Also, please ensure you bind this provider in your application.ts like mentioned here.
It should be something like this.

```
this.bind(
  AuthenticationBindings.Passport.OAUTH2_CLIENT_PASSWORD_VERIFIER,
).toProvider(ClientPasswordVerifyProvider);
// Add authentication component
this.component(AuthenticationComponent);
```

**Comment by edwinmp** [comment] 2019-06-04 13:22
I'm running into a similar issue. I've only implemented authentication via local password. It was bringing up the above error first, and now `Unhandled error in GET /: 500 Error: The key 'sf.passport.verifier.bearerToken' is not bound to any value in context application`.

I have bound the LocalPasswordVerifier in my `application.ts`, so now I'm wondering whether I have to implement them all to get one to work.

**Comment by samarpan-b** [comment] 2019-06-04 14:55
> I'm running into a similar issue. I've only implemented authentication via local password. It was bringing up the above error first, and now `Unhandled error in GET /: 500 Error: The key 'sf.passport.verifier.bearerToken' is not bound to any value in context application`.
> 
> I have bound the LocalPasswordVerifier in my `application.ts`, so now I'm wondering whether I have to implement them all to get one to work.

Are you using Strategy.Bearer in any of your controller ? if yes, then, you will require to implement the verifier for that as well.

On a side note, you will actually require at least 2 of the strategies to work perfectly. using local strategy you can verify the username password and return some token. That token will require to be validated in rest of the APIs. Hence, the bearer token strategy.

**Comment by samarpan-b** [comment] 2019-06-04 14:56
I'll try to add a sample where I can demonstrate implementation of some of the providers, not all. That may help.

**Comment by edwinmp** [comment] 2019-06-04 20:39
@samarpan-b I wasn't using the Bearer strategy before, but as you mentioned, I realised I'd need it, so I implemented it as well. Then I was getting `Unhandled error in GET /: 500 Error: The key 'sf.passport.verifier.resourceOwnerPassword' is not bound to any value in context application`
I had to add the resourceOwner strategy as well to get it working.

**Comment by samarpanB** [comment] 2019-06-05 04:10
Yes. I think the problem is they are missing a default implementation. I’ll add that. Thanks for raising the issue.

**Comment by samarpan-b** [comment] 2019-06-05 04:15
@edwinmp . Yes I see the issue now. It’s missing default implementation in case one doesn’t want to use some of them. I’ll add that. Thanks a lot for raising the issue.

**Comment by samarpan-b** [comment] 2019-06-13 11:15
This issue will be fixed with above PR. But it will be a breaking change. Main modification one would need in existing code is to add the Verify provider bindings after binding the Component. It was the reverse earlier.
This is how it should be now.
```ts
    // Add authentication component
    this.component(AuthenticationComponent);
    // Customize authentication verify handlers
    this.bind(
      AuthenticationBindings.Passport.LOCAL_PASSWORD_VERIFIER,
    ).toProvider(LocalPasswordVerifyProvider);
    this.bind(AuthenticationBindings.Passport.BEARER_TOKEN_VERIFIER).toProvider(
      BearerTokenVerifyProvider,
    );
```

You need to provide the bindings for only those which you use.

**Closed** 2019-06-13 11:17 UTC
Labels: good first issue
